apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  selector:
    matchLabels:
      app: my-spring-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: springboot-kubernetes
          image: my-spring-app-0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080