apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  ports:
    - protocol: "TCP"
      port: 8080        # The port inside the cluster
      targetPort: 8080  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: my-spring-app